# Conditionally create the Ingress for local; unneeded in GKE.
{{- if .Values.createIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Chart.Name}}-ingress
  namespace: {{ .Values.namespace | default "devstream" }}
spec:
  rules:
    - host: {{ .Values.net.host }}
      http:
        paths:
          - pathType: Prefix
            path: {{ .Values.net.contextPath }}
            backend:
              service:
                name: {{.Chart.Name}}
                port:
                  number: {{ .Values.net.servicePort }}
{{- end }}
