apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: portal-api
profiles:
  - name: local
    build:
      googleCloudBuild:
        projectId: devstream-shared-services-4179
        gradleImage: gradle:8.2.1-jdk17-alpine
      artifacts:
        - image: us-east4-docker.pkg.dev/devstream-shared-services-4179/application/devstream-portal-api
          jib:
            type: gradle
            project: service
            args:
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=cloud"
    deploy:
      helm:
        releases:
          - name: devstream-portal-api
            createNamespace: true
            chartPath: helm/portal-api
            # Ref: https://skaffold.dev/docs/deployers/helm/#image-configuration
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_portal_api}}"
              image.tag: "{{.IMAGE_TAG_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_portal_api}}@{{.IMAGE_DIGEST_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_portal_api}}"
            setValues:
              environment: local
            valuesFiles:
              - helm/portal-api/values.yaml
              - helm/portal-api/local.yaml
  - name: minikube
    activation:
      - kubeContext: minikube
    build:
      artifacts:
        - image: portal-api
          jib:
            type: gradle
            project: service
            args:
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=local"
    manifests:
      helm:
        releases:
          - name: portal-api
            createNamespace: true
            chartPath: helm/portal-api
            valuesFiles:
              - helm/portal-api/values.yaml
              - helm/portal-api/local.yaml
            setValues:
              environment: local
              net.readinessProbe.initialDelaySeconds: 30
              pullPolicy: IfNotPresent
            setValueTemplates:
              image.repository: portal-api
              image.tag: portal-api
    deploy:
      statusCheckDeadlineSeconds: 60
      tolerateFailuresUntilDeadline: true
      helm: {}
    portForward:
      - resourceType: service
        resourceName: portal-api
        namespace: devstream
        port: 80
        localPort: 8080
  - name: dev
    build:
      googleCloudBuild:
        projectId: devstream-shared-services-4179
        gradleImage: gradle:8.2.1-jdk17-alpine
      artifacts:
        - image: us-east4-docker.pkg.dev/devstream-shared-services-4179/application/devstream-portal-api
          jib:
            type: gradle
            project: service
            args:
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=cloud"
    deploy:
      helm:
        releases:
          - name: devstream-portal-api
            createNamespace: true
            chartPath: helm/portal-api
            # Ref: https://skaffold.dev/docs/deployers/helm/#image-configuration
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_portal_api}}"
              image.tag: "{{.IMAGE_TAG_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_portal_api}}@{{.IMAGE_DIGEST_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_portal_api}}"
            setValues:
              environment: dev
            valuesFiles:
              - helm/portal-api/values.yaml
              - helm/portal-api/dev.yaml
  - name: staging
    build:
      googleCloudBuild:
        projectId: devstream-shared-services-4179
        gradleImage: gradle:8.2.1-jdk17-alpine
      artifacts:
        - image: us-east4-docker.pkg.dev/devstream-shared-services-4179/application/devstream-portal-api
          jib:
            type: gradle
            project: service
            args:
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=cloud"
    deploy:
      helm:
        releases:
          - name: devstream-portal-api
            createNamespace: true
            chartPath: helm/portal-api
            # Ref: https://skaffold.dev/docs/deployers/helm/#image-configuration
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_portal_api}}"
              image.tag: "{{.IMAGE_TAG_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_portal_api}}@{{.IMAGE_DIGEST_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_portal_api}}"
            setValues:
              environment: staging
            valuesFiles:
              - helm/portal-api/values.yaml
              - helm/portal-api/staging.yaml
  - name: prod
    build:
      googleCloudBuild:
        projectId: devstream-shared-services-4179
        gradleImage: gradle:8.2.1-jdk17-alpine
      artifacts:
        - image: us-east4-docker.pkg.dev/devstream-shared-services-4179/application/devstream-portal-api
          jib:
            type: gradle
            project: service
            args:
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=cloud"
    deploy:
      helm:
        releases:
          - name: devstream-portal-api
            createNamespace: true
            chartPath: helm/portal-api
            # Ref: https://skaffold.dev/docs/deployers/helm/#image-configuration
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_portal_api}}"
              image.tag: "{{.IMAGE_TAG_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_portal_api}}@{{.IMAGE_DIGEST_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_portal_api}}"
            setValues:
              environment: prod
            valuesFiles:
              - helm/portal-api/values.yaml
              - helm/portal-api/prod.yaml
