server:
  servlet:
    context-path: /portal
spring:
  sleuth:
    sampler:
      probability: ${OTEL_SAMPLER_PROBABILITY:1.0} # Valid values [0.0 - 1.0]
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
  jackson:
    serialization:
      write-dates-with-zone-id: true
      write-dates-as-timestamps: false
    deserialization:
      adjust_dates_to_context_time-zone: false

management:
  endpoints:
    web:
      cors:
        allow-credentials: true
        allowed-origins: ${ALLOWED_ORIGINS}
        allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allowed-headers: "*"

cerbos:
  uri: ${CERBOS_URI}


